# Generated by Django 6.1.1 on 2026-09-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_accessed_date',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
