# Generated by Django 6.1.1 on 2026-09-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshapp', '0002_user_last_accessed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_accessed_date',
            field=models.CharField(blank=True, default='', max_length=128, null=True),
        ),
    ]
