# Generated by Django 6.1.1 on 2026-10-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshapp', '0003_alter_user_last_accessed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('subtitle', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
