# Generated by Django 6.1.1 on 2026-09-23 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshapp', '0004_remove_message_author_todolist_user_aimessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='freshapp.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='RefreshingTask',
        ),
    ]
