# Generated by Django 6.1.1 on 2026-09-23 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshapp', '0005_task_completed_dates_task_parent_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshingTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='freshapp.task')),
            ],
            bases=('freshapp.task',),
        ),
    ]
