# Generated by Django 6.1.1 on 2026-09-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshapp', '0006_refreshingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshingtask',
            name='extra_field',
            field=models.CharField(default='default', max_length=512),
        ),
    ]
