# Generated by Django 6.1.1 on 2026-09-23 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshapp', '0007_refreshingtask_extra_field'),
    ]

    operations = [
    ]
