# Generated by Django 6.1.1 on 2026-09-23 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshapp', '0008_remove_task_completed_dates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshingTask',
        ),
    ]
