# Generated by Django 6.1.1 on 2026-09-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshapp', '0009_delete_refreshingtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_for_good',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_dates',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
