# Generated by Django 6.1.1 on 2026-09-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshapp', '0010_task_completed_for_good_alter_task_completed_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='refreshing',
            field=models.BooleanField(default=False),
        ),
    ]
